platform :ios, '6.0'
pod 'AFNetworking', '~> 1.3.2'
pod 'TouchJSON', '~> 1.1'
pod 'OpenUDID'
pod 'SDWebImage', :head
pod 'LKDBHelper', :head
pod 'MBProgressHUD', '~> 0.8'
pod 'NSDate+Helper'
pod 'IQKeyboardManager'
pod 'MMDrawerController', '~> 0.5.7'
pod 'RMSwipeTableViewCell'